/* This file was autogenerated by openCONFIGURATOR-1.4.1 on 01-Mar-2018 15:03:41 */
#ifndef XAP_h
#define XAP_h

# define COMPUTED_PI_OUT_SIZE 12
typedef struct
{
	unsigned CN1_M00_DigitalInput_00h_AU8_DigitalInput01:8;
	unsigned CN1_M00_DigitalInput_00h_AU8_DigitalInput02:8;
	unsigned CN2_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned CN3_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned CN4_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned CN5_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned CN6_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned CN7_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned CN8_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned PADDING_VAR_1:24;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 12
typedef struct
{
	unsigned CN1_M00_DigitalOutput_00h_AU8_DigitalOutput01:8;
	unsigned CN1_M00_DigitalOutput_00h_AU8_DigitalOutput02:8;
	unsigned CN2_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned CN3_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned CN4_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned CN5_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned CN6_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned CN7_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned CN8_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned PADDING_VAR_1:24;
} PI_IN;

#endif
